sudo: required

matrix:
    include:
        - os: linux
          dist: trusty
          language: python
          python: 2.7
          go: 1.8
          group: edge
        - os: osx
          language: pyhthon
          python: 2.7
          go: 1.8

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                                                ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3                                                       ; fi
    - export GOPATH="`pwd`/golang:$GOPATH"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./test/dependencies_osx.sh                                                 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/dependencies_linux.sh                                             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100 ; fi

script:
    - export GOPATH="`pwd`/golang:$GOPATH"
    - mkdir -p golang/src/github.com/CiscoDevNet/ydk-go/ydk
    - cp -r sdk/go/core/ydk/* golang/src/github.com/CiscoDevNet/ydk-go/ydk/
    - cp -r sdk/go/packages/ydk/* golang/src/github.com/CiscoDevNet/ydk-go/ydk/
    - sudo ./test/tests.sh

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) ; fi  # Uploading python report to CodeCov

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ${TRAVIS_BUILD_DIR}/sdk/cpp/core/build ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --directory . --capture --output-file coverage.info ; fi # capture coverage info
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --remove coverage.info '/usr/*' '/Applications/*' --output-file coverage.info ; fi # filter out system
    #- lcov --list coverage.info #debug info
    # Uploading cpp report to CodeCov
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports" ; fi
